CREATE SEQUENCE vanzare2seq START WITH 1 MINVALUE 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/
CREATE SEQUENCE vanzare3seq START WITH 1 MINVALUE 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/
--as sys
CREATE OR REPLACE PROCEDURE sleep(seconds NUMBER) AS
BEGIN
  DBMS_LOCK.SLEEP(seconds);
END;
/
 
CREATE OR REPLACE public synonym sleep FOR sleep;
 
GRANT EXECUTE ON sleep TO public;